Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2020-10, with the labels that each got.

#45 when deleting objects, only the object_name is required
  hacking/update_examples_and_tests.sh
  plugins/modules/icinga_command.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_notification.py
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_command.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_command_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_user.yml
Labels: bug

#47 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#48 Add Support for Zones and Endpoints
  README.md
  examples/icinga_endpoint.yml
  examples/icinga_zone.yml
  plugins/modules/icinga_endpoint.py
  plugins/modules/icinga_zone.py
  roles/ansible_icinga/README.md
  roles/ansible_icinga/defaults/main.yml
  roles/ansible_icinga/tasks/icinga_endpoint.yml
  roles/ansible_icinga/tasks/icinga_zone.yml
  roles/ansible_icinga/tasks/main.yml
  tests/integration/targets/icinga/checkmode.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_endpoint.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_zone.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_endpoint.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_zone.yml
  tests/integration/targets/icinga/roles/icinga/tasks/main.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_endpoint.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_zone.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_endpoint.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_zone.yml
Labels: enhancement, minor

#53 add check_command arg to service_apply module
  plugins/modules/icinga_service_apply.py
Labels: enhancement, minor

#54 update examples and tests so they can actually be deployed
  examples/icinga_host.yml
  examples/icinga_service.yml
  examples/icinga_service_apply.yml
  examples/icinga_service_template.yml
  plugins/modules/icinga_host.py
  plugins/modules/icinga_service.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_service.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_service_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_service.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_service_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/main.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_service.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_service_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_service.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_service_template.yml
Labels: enhancement

#55 allow using whitespaces in object names
  examples/icinga_service.yml
  plugins/module_utils/icinga.py
  plugins/modules/icinga_service.py
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_service.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_service.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_service.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_service.yml
Labels: bug

#56 Add support for notes and notes_url to all relevant objects
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  plugins/modules/icinga_service.py
  plugins/modules/icinga_service_template.py
  roles/ansible_icinga/README.md
  roles/ansible_icinga/tasks/icinga_host.yml
  roles/ansible_icinga/tasks/icinga_host_template.yml
  roles/ansible_icinga/tasks/icinga_service.yml
  roles/ansible_icinga/tasks/icinga_service_template.yml
Labels: enhancement, minor
