Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2020-06, with the labels that each got.

#10 fix issue #9 - define assing_filter as string
  plugins/modules/icinga_notification.py
Labels: bug, patch

#11 remove unused intermediate assignments
  plugins/modules/icinga_command.py
  plugins/modules/icinga_command_template.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_hostgroup.py
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  plugins/modules/icinga_servicegroup.py
  plugins/modules/icinga_timeperiod.py
  plugins/modules/icinga_user.py
  plugins/modules/icinga_user_template.py
Labels: enhancement, patch

#12 github-action to automatically create release-drafts
  .github/workflows/release.yml
Labels: enhancement, patch

#15 add steps to update galaxy.yml in publish action
  .github/workflows/galaxy.yml
Labels: enhancement, patch

#16 try to improve error messages
  plugins/module_utils/icinga.py
Labels: enhancement, patch

#17 added required ansible version to readme.md
  README.md
Labels: enhancement, patch

#18 further improve error messages for different errors
  plugins/module_utils/icinga.py
Labels: enhancement, patch

#19 add troubleshooting section
  README.md
Labels: documentation, enhancement, patch

#21 add gitattributes because of windows line endings
  .gitattributes
Labels: enhancement, patch

#20 add icinga_host_template
  README.md
  examples/icinga_host_template.yml
  plugins/modules/icinga_host_template.py
Labels: enhancement, minor

#23 do not require import and check_command in host_template
  plugins/modules/icinga_host_template.py
Labels: bug, patch

#22 Add proper linting
  .github/workflows/ansible-lint.yml
  .github/workflows/galaxy.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .gitignore
  .yamllint
  examples/icinga_command.yml
  examples/icinga_command_template.yml
  examples/icinga_host.yml
  examples/icinga_host_template.yml
  examples/icinga_hostgroup.yml
  examples/icinga_notification.yml
  examples/icinga_service_apply.yml
  examples/icinga_service_template.yml
  examples/icinga_service_timeperiod.yml
  examples/icinga_service_user.yml
  examples/icinga_servicegroup.yml
  examples/icinga_timeperiod.yml
  examples/icinga_user.yml
  examples/icinga_user_template.yml
  examples/update_examples.sh
  galaxy.yml
  plugins/module_utils/icinga.py
  plugins/modules/icinga_command.py
  plugins/modules/icinga_command_template.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  plugins/modules/icinga_hostgroup.py
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  plugins/modules/icinga_servicegroup.py
  plugins/modules/icinga_timeperiod.py
  plugins/modules/icinga_user.py
  plugins/modules/icinga_user_template.py
  requirements.txt
  test-requirements.txt
  tests/sanity/ignore-2.9.txt
  tox.ini
Labels: enhancement, patch

#26 do not set zone to master in host and hosttemplate
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
Labels: patch

#27 Use ansible-test to run integration tests
  .github/workflows/main.yml
  tests/integration/targets/icinga/tasks/icinga_command.yml
  tests/integration/targets/icinga/tasks/icinga_command_template.yml
  tests/integration/targets/icinga/tasks/icinga_host.yml
  tests/integration/targets/icinga/tasks/icinga_host_template.yml
  tests/integration/targets/icinga/tasks/icinga_hostgroup.yml
  tests/integration/targets/icinga/tasks/icinga_notification.yml
  tests/integration/targets/icinga/tasks/icinga_service_apply.yml
  tests/integration/targets/icinga/tasks/icinga_service_template.yml
  tests/integration/targets/icinga/tasks/icinga_servicegroup.yml
  tests/integration/targets/icinga/tasks/icinga_timeperiod.yml
  tests/integration/targets/icinga/tasks/icinga_user.yml
  tests/integration/targets/icinga/tasks/icinga_user_template.yml
  tests/integration/targets/icinga/tasks/main.yml
  tests/integration/targets/icinga/vars/main.yml
  tests/integration/test.yml
Labels: enhancement, patch
