Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2020-12, with the labels that each got.

#66 improve support for API parameters
  examples/icinga_host.yml
  examples/icinga_host_template.yml
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  roles/ansible_icinga/tasks/icinga_host.yml
  roles/ansible_icinga/tasks/icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_host_template.yml
Labels: enhancement, minor

#68 add vars option to icinga_notification
  examples/icinga_notification.yml
  plugins/modules/icinga_notification.py
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_notification.yml
Labels: enhancement, minor

#69 fixed "command is missing" while trying to create a command
  plugins/modules/icinga_command.py
Labels: bug, patch

#77 added wished files and directories to build_ignore list
  galaxy.yml
Labels: enhancement
