Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2020-07, with the labels that each got.

#28 Ansible icinga role
  .yamllint
  README.md
  roles/ansible-icinga/README.md
  roles/ansible-icinga/defaults/main.yml
  roles/ansible-icinga/meta/main.yml
  roles/ansible-icinga/tasks/icinga_command.yml
  roles/ansible-icinga/tasks/icinga_command_template.yml
  roles/ansible-icinga/tasks/icinga_host.yml
  roles/ansible-icinga/tasks/icinga_host_template.yml
  roles/ansible-icinga/tasks/icinga_hostgroup.yml
  roles/ansible-icinga/tasks/icinga_notification.yml
  roles/ansible-icinga/tasks/icinga_service_apply.yml
  roles/ansible-icinga/tasks/icinga_service_template.yml
  roles/ansible-icinga/tasks/icinga_servicegroup.yml
  roles/ansible-icinga/tasks/icinga_timeperiod.yml
  roles/ansible-icinga/tasks/icinga_user.yml
  roles/ansible-icinga/tasks/icinga_user_template.yml
  roles/ansible-icinga/tasks/main.yml
  tox.ini
Labels: documentation, enhancement, minor

#29 replace hyphen in role name with underscore
  .yamllint
  README.md
  roles/ansible_icinga/README.md
  roles/ansible_icinga/defaults/main.yml
  roles/ansible_icinga/meta/main.yml
  roles/ansible_icinga/tasks/icinga_command.yml
  roles/ansible_icinga/tasks/icinga_command_template.yml
  roles/ansible_icinga/tasks/icinga_host.yml
  roles/ansible_icinga/tasks/icinga_host_template.yml
  roles/ansible_icinga/tasks/icinga_hostgroup.yml
  roles/ansible_icinga/tasks/icinga_notification.yml
  roles/ansible_icinga/tasks/icinga_service_apply.yml
  roles/ansible_icinga/tasks/icinga_service_template.yml
  roles/ansible_icinga/tasks/icinga_servicegroup.yml
  roles/ansible_icinga/tasks/icinga_timeperiod.yml
  roles/ansible_icinga/tasks/icinga_user.yml
  roles/ansible_icinga/tasks/icinga_user_template.yml
  roles/ansible_icinga/tasks/main.yml
Labels: patch

#31 update examples and bash script for new testing paths
  examples/icinga_host.yml
  hacking/update_examples_and_tests.sh
Labels: patch

#33 make local testing without ansible-test easier
  tests/integration/targets/icinga/meta/main.yml
  tests/integration/test.yml
Labels: enhancement, patch
