Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2021-06, with the labels that each got.

#120 add info about documentation
  README.md
Labels: documentation, patch

#121 add period to notification task
  roles/ansible_icinga/README.md
  roles/ansible_icinga/tasks/icinga_notification.yml
Labels: minor

#125 add notification_template to role
  roles/ansible_icinga/README.md
  roles/ansible_icinga/tasks/icinga_notification_template.yml
  roles/ansible_icinga/tasks/main.yml
Labels: enhancement, minor
