Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2021-08, with the labels that each got.

#131 Docs and tests update
  examples/icinga_command.yml
  examples/icinga_command_template.yml
  examples/icinga_timeperiod_template_info.yml
  plugins/modules/icinga_command.py
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_command.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_command_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_command.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_command_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_timeperiod_template_info.yml
  tests/integration/targets/icinga/roles/icinga/tasks/no_query_icinga_timeperiod_template_info.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_command.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_command_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_command.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_command_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_timeperiod_template_info.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_query_icinga_timeperiod_template_info.yml
Labels: documentation, patch

#132 Add event_command parameter to icinga_service_apply module
  examples/icinga_service_apply.yml
  plugins/modules/icinga_service_apply.py
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_service_apply.yml
Labels: enhancement, minor

#133 Add event_command parameter to service apply playbook to enable usage
  roles/ansible_icinga/tasks/icinga_service_apply.yml
Labels: enhancement, minor

#135 Changed place in the creation order of service object in ansible_icinga role
  roles/ansible_icinga/tasks/main.yml
Labels: bug, patch
