Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2021-11, with the labels that each got.

#147 add resolve option to inventory-plugin
  plugins/inventory/icinga_director_inventory.py
Labels: enhancement

#146 Add Icinga scheduled downtime module
  examples/icinga_scheduled_downtime.yml
  plugins/doc_fragments/__pycache__/common_options.cpython-38.pyc
  plugins/modules/icinga_scheduled_downtime.py
  roles/ansible_icinga/README.md
  roles/ansible_icinga/tasks/icinga_scheduled_downtime.yml
  roles/ansible_icinga/tasks/main.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_command_info.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_command_template_info.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_scheduled_downtime.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_scheduled_downtime.yml
  tests/integration/targets/icinga/roles/icinga/tasks/main.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_command_info.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_command_template_info.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_scheduled_downtime.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_scheduled_downtime.yml
Labels: enhancement, minor

#150 added a fix for the new scheduled_downtime module
  roles/ansible_icinga/defaults/main.yml
  roles/ansible_icinga/tasks/icinga_scheduled_downtime.yml
Labels: bug, patch
