Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2021-02, with the labels that each got.

#103 update readme with new stuff
  README.md
Labels: documentation

#110 add new options to notification and notification template
  examples/icinga_notification.yml
  examples/icinga_notification_template.yml
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_notification_template.py
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_notification_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_notification_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_notification_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_notification_template.yml
Labels: enhancement, minor

#112 update notification modules - add option user_groups
  examples/icinga_notification.yml
  examples/icinga_notification_template.yml
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_notification_template.py
  roles/ansible_icinga/tasks/icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_notification_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_notification_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_notification_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_notification.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_notification_template.yml
Labels: enhancement
