Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2021-01, with the labels that each got.

#78 use doc_fragments for modules documentation
  plugins/doc_fragments/auth_options.py
  plugins/modules/icinga_command.py
  plugins/modules/icinga_command_template.py
  plugins/modules/icinga_endpoint.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  plugins/modules/icinga_hostgroup.py
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_notification_template.py
  plugins/modules/icinga_service.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  plugins/modules/icinga_servicegroup.py
  plugins/modules/icinga_timeperiod.py
  plugins/modules/icinga_user.py
  plugins/modules/icinga_user_template.py
  plugins/modules/icinga_zone.py
Labels: documentation, enhancement

#80 add name alias for object_name
  plugins/modules/icinga_command.py
  plugins/modules/icinga_command_template.py
  plugins/modules/icinga_endpoint.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  plugins/modules/icinga_hostgroup.py
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_notification_template.py
  plugins/modules/icinga_service.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  plugins/modules/icinga_servicegroup.py
  plugins/modules/icinga_timeperiod.py
  plugins/modules/icinga_user.py
  plugins/modules/icinga_user_template.py
  plugins/modules/icinga_zone.py
Labels: enhancement, minor

#82 add version_added to modules and module options
  plugins/modules/icinga_command.py
  plugins/modules/icinga_command_template.py
  plugins/modules/icinga_endpoint.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  plugins/modules/icinga_hostgroup.py
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_notification_template.py
  plugins/modules/icinga_service.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  plugins/modules/icinga_servicegroup.py
  plugins/modules/icinga_timeperiod.py
  plugins/modules/icinga_user.py
  plugins/modules/icinga_user_template.py
  plugins/modules/icinga_zone.py
Labels: documentation, enhancement

#81 add docstrings to the functions of the icinga class
  plugins/module_utils/icinga.py
Labels: documentation, enhancement

#84 change class to make compatible for python2
  plugins/module_utils/icinga.py
Labels: enhancement

#83 fix spelling in module docs
  plugins/modules/icinga_command.py
  plugins/modules/icinga_command_template.py
  plugins/modules/icinga_endpoint.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  plugins/modules/icinga_hostgroup.py
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_notification_template.py
  plugins/modules/icinga_service.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  plugins/modules/icinga_servicegroup.py
  plugins/modules/icinga_timeperiod.py
  plugins/modules/icinga_user.py
  plugins/modules/icinga_user_template.py
  plugins/modules/icinga_zone.py
Labels: documentation

#86 Update tests
  .github/workflows/main.yml
  plugins/module_utils/icinga.py
Labels: enhancement

#88 remove unneeded return values
  plugins/modules/icinga_command.py
  plugins/modules/icinga_command_template.py
  plugins/modules/icinga_endpoint.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  plugins/modules/icinga_hostgroup.py
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_notification_template.py
  plugins/modules/icinga_service.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  plugins/modules/icinga_servicegroup.py
  plugins/modules/icinga_timeperiod.py
  plugins/modules/icinga_user.py
  plugins/modules/icinga_user_template.py
  plugins/modules/icinga_zone.py
Labels: documentation, minor

#93 remove period from short description
  plugins/modules/icinga_command_template.py
  plugins/modules/icinga_endpoint.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  plugins/modules/icinga_hostgroup.py
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_notification_template.py
  plugins/modules/icinga_service.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  plugins/modules/icinga_servicegroup.py
  plugins/modules/icinga_timeperiod.py
  plugins/modules/icinga_user.py
  plugins/modules/icinga_user_template.py
  plugins/modules/icinga_zone.py
Labels: documentation

#92 add back url parameter
  plugins/doc_fragments/common_options.py
  plugins/modules/icinga_command.py
  plugins/modules/icinga_command_template.py
  plugins/modules/icinga_endpoint.py
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  plugins/modules/icinga_hostgroup.py
  plugins/modules/icinga_notification.py
  plugins/modules/icinga_notification_template.py
  plugins/modules/icinga_service.py
  plugins/modules/icinga_service_apply.py
  plugins/modules/icinga_service_template.py
  plugins/modules/icinga_servicegroup.py
  plugins/modules/icinga_timeperiod.py
  plugins/modules/icinga_user.py
  plugins/modules/icinga_user_template.py
  plugins/modules/icinga_zone.py
Labels: bug, patch

#67 Add execution parms
  examples/icinga_service_apply.yml
  plugins/modules/icinga_service_apply.py
  roles/ansible_icinga/tasks/icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_service_apply.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_service_apply.yml
Labels: enhancement, minor

#95 Add check_interval parameter to host_template
  examples/icinga_host_template.yml
  plugins/modules/icinga_host_template.py
  roles/ansible_icinga/README.md
  roles/ansible_icinga/tasks/icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_host_template.yml
Labels: enhancement, minor
