Repository telekom-mms/ansible-collection-icinga-director, pull requests merged in 2022-03, with the labels that each got.

#159 Fix sanity tests
  plugins/inventory/icinga_director_inventory.py
Labels: patch

#161 role: add check_command to icinga_service_apply
  roles/ansible_icinga/tasks/icinga_service_apply.yml
Labels: bug, patch

#158 Added missing fields to 'icinga_host' and 'icinga_host_template'
  docs/icinga_host.rst
  docs/icinga_host_template.rst
  examples/icinga_host.yml
  examples/icinga_host_template.yml
  plugins/modules/icinga_host.py
  plugins/modules/icinga_host_template.py
  roles/ansible_icinga/tasks/icinga_host.yml
  roles/ansible_icinga/tasks/icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/absent_icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_host_icinga_host_template.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_host.yml
  tests/integration/targets/icinga/roles/icinga/tasks/wrong_pass_icinga_host_template.yml
Labels: enhancement, minor

#162 Test more ansible versions
  .github/workflows/main.yml
Labels: enhancement, patch
